import { DIContainer } from '@app/common/di';
import { UserService } from './UserService';
import { GameService } from './GameService';
import { ConfigService } from './ConfigService';
import { SquadService } from './SquadService';
import { LeagueService } from './LeagueService';
import { BotHunterService } from './BotHunterService';
import { QuestService } from './QuestService';
import { AuctionService } from './AuctionService';
import { AnalyticsService } from './AnalyticsService';
import { CacheService } from './CacheService';
import { ShopService } from './ShopService';
import { СheatСodeService } from './СheatСodeService';
import { SoundService } from './SoundService';
import { AuthService } from './AuthService';

export const cacheService = DIContainer.resolve(CacheService);
export const authService = DIContainer.resolve(AuthService);
export const userService = DIContainer.resolve(UserService);
export const configService = DIContainer.resolve(ConfigService);
export const gameService = DIContainer.resolve(GameService);
export const squadService = DIContainer.resolve(SquadService);
export const leagueService = DIContainer.resolve(LeagueService);
export const botHunterService = DIContainer.resolve(BotHunterService);
export const questService = DIContainer.resolve(QuestService);
export const auctionService = DIContainer.resolve(AuctionService);
export const analyticsService = DIContainer.resolve(AnalyticsService);
export const shopService = DIContainer.resolve(ShopService);
export const cheatСodeService = DIContainer.resolve(СheatСodeService);
export const soundService = DIContainer.resolve(SoundService);
